[FEATURE] Tableau Hyper
Nike-Inc/koheesio pull request #49
Opened 2024-06-10 16:45 UTC by maxim-mityutko

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-09-02 08:53 UTC, dannymeijer requested changes
I like the code. Please have a look at the docstrings though. Would like to see every class have a docstring, and ensure docstring formats are Numpy style.

2024-09-02 08:53 UTC, dannymeijer commented on src/koheesio/integrations/spark/tableau/hyper.py
> +    Reference:
Please reformat this docstring to be Numpy compliant.

- Change headings to be like this
    > Reference
    > ----------
- Ensure the Example heading is plural (Examples)
- Put the code example in a code-block

2024-09-02 08:53 UTC, dannymeijer commented on src/koheesio/integrations/spark/tableau/hyper.py
> +    Read one or multiple parquet files and write them to a Hyper file.
same as above

2024-09-02 08:53 UTC, dannymeijer commented on src/koheesio/integrations/spark/tableau/server.py
> +class TableauServer(Step):
Please add docstring

2024-09-02 08:53 UTC, dannymeijer commented on src/koheesio/integrations/spark/tableau/server.py
> +class TableauHyperPublisher(TableauServer):
Please add docstring

2024-09-03 11:38 UTC, dannymeijer commented on src/koheesio/integrations/spark/tableau/hyper.py
> +        hw.hyper_path
missing the closing `````

2024-09-03 11:56 UTC, maxim-mityutko commented on src/koheesio/integrations/spark/tableau/hyper.py
> +        hw.hyper_path
added it, thanks for spotting!

2024-09-04 07:58 UTC, dannymeijer approved these changes

2024-09-04 12:42 UTC, merged