[FEATURE] - Generic file writer
Nike-Inc/koheesio pull request #54
Opened 2024-07-09 07:39 UTC by riccamini

Generic file writer

## Description
This PR provides a generic FileWriter class for several file formats and can be configured with any required option

## Related Issue
https://github.com/Nike-Inc/koheesio/issues/52

## Motivation and Context
Koheesio is currently shipping with the FileLoader which allows to read any file format specifying any needed option. The same feature, on the other hand, is missing on the writer side as there's no current class that supports generic file writing

## How Has This Been Tested?
Unit tests with mocks for DataFrameWriter calls

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-07-09 08:41 UTC, dannymeijer requested changes

2024-07-09 08:41 UTC, dannymeijer commented on src/koheesio/spark/writers/file_writer.py
> +    Example:
For formatting purposes, change this to a header:
~~~markdown
Examples
--------
...
~~~

2024-07-09 08:41 UTC, dannymeijer commented on src/koheesio/spark/writers/file_writer.py
> +        ```python
... and also decent this one level once you change to header as above

2024-07-09 08:41 UTC, dannymeijer commented on src/koheesio/spark/writers/file_writer.py
> +    Example:
Same here

2024-07-09 08:41 UTC, dannymeijer commented on src/koheesio/spark/writers/file_writer.py
> +    Example:
Etc.

2024-07-09 08:41 UTC, dannymeijer commented on src/koheesio/spark/writers/file_writer.py
> +    Example:
Etc.

2024-07-09 08:41 UTC, dannymeijer commented on src/koheesio/spark/writers/file_writer.py
> +    Example:
Etc.

2024-07-09 08:41 UTC, dannymeijer commented on src/koheesio/spark/writers/file_writer.py
> +    Example:
Etc.

2024-07-09 08:41 UTC, dannymeijer commented on src/koheesio/spark/writers/file_writer.py
> +    Example:
Etc.

2024-07-09 14:46 UTC, riccamini commented
@dannymeijer Hope now it renders well

2024-07-11 07:42 UTC, dannymeijer approved these changes

2024-08-30 08:09 UTC, pariksheet approved these changes
Cool stuff.. LGTM

2024-09-02 08:33 UTC, merged