Release/0.9
Nike-Inc/koheesio pull request #97
Opened 2024-11-08 14:31 UTC by dannymeijer

This PR is to merge the 0.9 release work up to main (for final release) once we are ready to do so.

2024-11-08 14:32 UTC, dannymeijer commented
marking this as blocked until we feel ready enough to actuate the release.

2024-11-12 08:58 UTC, dannymeijer commented
Observed a bug in which logs are logged twice. Needs to be investigated

2024-11-26 22:33 UTC, mikita-sakalouski requested changes
We should adjust documentation or ReadMe, to mention that spark connect is supported, fully on databricks due to the custom delta package and partionaly on open source of Apache Spark till version PySpark

2024-11-27 16:11 UTC, riccamini reviewed
Some comments mostly related to imports

2024-11-27 16:11 UTC, riccamini commented on tests/spark/readers/test_jdbc.py
I see the SparkSession being import from pyspark.sql. This is also present in other test scripts (test_lookup, test_hana). Is this ok because locally we never rely on SparkConnect? Do you see a case in which we should set up the scripts so that they can be tested with both the sessions? (and dataframe classes of course)

2024-11-29 14:03 UTC, dannymeijer commented on src/koheesio/integrations/spark/sftp.py
> +    buffer_writer: Optional[PandasJsonBufferWriter] = Field(default=None, validate_default=False)
This is related to how pydantic works. For a it to allow a default to be None, it requires the type to be Optional.

2024-11-29 14:03 UTC, dannymeijer commented on src/koheesio/integrations/spark/snowflake.py
> +Every class in this module is a subclass of `Step` or `Task` and is used to perform operations on Snowflake.
Correct - the Task class does not exist anymore - good callout. I will adjust the doc

2024-11-29 14:07 UTC, dannymeijer commented on src/koheesio/integrations/spark/snowflake.py
> +class SynchronizeDeltaToSnowflakeTask(SnowflakeSparkStep):
Will create an issue for this so we can address it in 1.0

2024-11-29 14:08 UTC, dannymeijer commented on src/koheesio/integrations/spark/snowflake.py
> +class SynchronizeDeltaToSnowflakeTask(SnowflakeSparkStep):
Created #136

2024-11-29 14:09 UTC, dannymeijer commented on src/koheesio/spark/__init__.py
> +)
it's to keep the imports simpler. Import from the spark module is just a bit easier to read and understand.

2024-11-29 14:09 UTC, dannymeijer commented on src/koheesio/spark/readers/delta.py
> +from pyspark.sql import DataFrameReader
In due time. The code is currently unaffected with it being from the "non connect" part of Spark.

2024-11-29 14:17 UTC, dannymeijer commented on src/koheesio/integrations/spark/snowflake.py
> +Every class in this module is a subclass of `Step` or `Task` and is used to perform operations on Snowflake.
Created #135 with PR #138

2024-11-29 14:20 UTC, dannymeijer commented on tests/spark/readers/test_jdbc.py
This is a dead import. Let me fix it right quick - good catch (although it doesn't affect functionality of the test)

2024-11-29 14:29 UTC, dannymeijer commented on tests/spark/readers/test_jdbc.py
Created #139 with PR #140

2024-11-29 14:32 UTC, mikita-sakalouski submitted a review, later dismissed

2024-11-29 14:43 UTC, riccamini approved these changes
Looks good to me 🛫

2024-11-29 14:50 UTC, merged